### ISSUE TITLE
Link to documentation needs to be added to About area on repo page

### ISSUE THREAD

**Issue by PipKat** [pyansys/grantami-bomanalytics#260]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

While the README file for this repo has a link to the documentation at https://grantami.docs.pyansys.com/, there is no link in the About area of the repo page. This link is available in the About location for all other public PyAnsys libraries.

### 📝 Steps to reproduce

Go to repo page and see that there is no doc link in the About area.

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
N/A
```

**Comment by ludovicsteinbach** [comment]
Thanks for pointing that out, I've added the link.
